version: '3.3'
services:
  db:
    image: mysql:8.0.23
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: cuidapet_db
      MYSQL_ROOT_PASSWORD: cuidapet
    volumes:
      - ../mysql_data:/var/lib/mysql