name: cuidapet_api
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.3 <3.0.0'

dependencies:
  args: ^2.0.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  shelf_router_generator: ^1.0.4
  dotenv: ^3.0.0
  mysql1: ^0.20.0
  get_it: ^7.2.0
  logger: ^1.1.0
  injectable: ^2.1.0
  jaguar_jwt: ^3.0.0
  http: ^0.13.5
  
  #
  # Chamando a versão direto do github
  #
  # shelf_router_generator:
  #   git:
  #     url: https://github.com/dart-lang/shelf.git
  #     path: shelf_router_generator

dev_dependencies:
  lints: ^2.0.0
  test: ^1.15.0
  build_runner: ^2.3.2
  injectable_generator: ^2.1.2

# TODO SOBREESCREVER VERSÕES 
# dependency_overrides:
#   logging: ^1.0.0
#   crypto: ^3.0.0